apiVersion: v1
kind: Service
metadata:
  labels:
    app: helloworld
  name: helloworld12
  namespace: app-1
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: helloworld
  type: LoadBalancer
