bases:
- ../../../../../../base
namePrefix: store-2-
namespace: app-1
images:
- name: signalsciences/example-helloworld:latest
  newName: kubegoldenguide/nginx-hostname
  newTag: 1.0.1
commonAnnotations:
  configmanagement.gke.io/cluster-selector: "selector-store-2"
# resource:
# - ../../../../../clusterregistry/cluster-selector.yaml